<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	  <Nullable>disable</Nullable>
	  <AssemblyName>Abc.Soft.Todo</AssemblyName>
	  <RootNamespace>Abc.Soft.Todo</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Abc.Soft.Todo-35c58480-fa71-471a-9081-9e64e11e1cbc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abc.Soft.Todo.Client\Abc.Soft.Todo.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13" />
  </ItemGroup>

</Project>
